export const ERROR = 'ERROR';


// Catalog Browsing Routes
export const LOAD_FEATURED_PRODUCTS = 'LOAD_FEATURED_PRODUCTS';
export const LOAD_BEST_SELLING_PRODUCTS = 'LOAD_BEST_SELLING_PRODUCTS';
export const LOAD_CATALOG_PRODUCTS = 'LOAD_CATALOG_PRODUCTS';
export const LOAD_PRODUCT_DETAILS = 'LOAD_PRODUCT_DETAILS';


// User Account Management Routes
export const LOAD_USER_PROFILE = 'LOAD_USER_PROFILE';
export const UPDATE_USER_PROFILE = 'UPDATE_USER_PROFILE';
// export const DELETE_USER_PROFILE = 'DELETE_USER_PROFILE';


// Merchant Account Management Routes
export const LOAD_MERCHANT_PROFILE = 'LOAD_MERCHANT_PROFILE';
export const UPDATE_MERCHANT_PROFILE = 'UPDATE_MERCHANT_PROFILE';
// export const DELETE_MERCHANT_PROFILE = 'DELETE_MERCHANT_PROFILE';


// Cart Management Routes
export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
export const UPDATE_PRODUCT_QUANTITY = 'UPDATE_PRODUCT_QUANTITY';
export const REMOVE_PRODUCT_FROM_CART = 'REMOVE_PRODUCT_FROM_CART';
export const APPLY_COUPON_TO_PRODUCT = 'APPLY_COUPON_TO_PRODUCT';


// Order Management Routes
export const CREATE_NEW_ORDER = 'CREATE_NEW_ORDER';
export const READ_ORDER_DATA = 'READ_ORDER_DATA';
export const READ_USER_ORDERS = 'READ_USER_ORDERS';


// Merchant Browsing Routes
export const LOAD_MERCHANT_DETAILS = 'LOAD_MERCHANT_DETAILS';
export const LOAD_MERCHANT_LIST = 'LOAD_MERCHANT_LIST';


// Gathering Management Routes
export const LOAD_MERCHANT_GATHERINGS = 'LOAD_MERCHANT_GATHERINGS'