export const ERROR = 'ERROR';


export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
export const UPDATE_PRODUCT_IN_CART = 'UPDATE_PRODUCT_IN_CART';
export const REMOVE_PRODUCT_FROM_CART = 'REMOVE_PRODUCT_FROM_CART';
export const READ_PRODUCTS_FROM_CART = 'READ_PRODUCTS_FROM_CART';
export const APPLY_COUPON_TO_PRODUCT = 'APPLY_COUPON_TO_PRODUCT';

export const SYSTEM_ORDER_CREATED = 'SYSTEM_ORDER_CREATED';
